config/routes.rb
Rails.application.routes.draw do
  
  #root route
  root 'demo#index'

  #Resourceful Routes
  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  #simple route 
  get 'demo/index' 
  get 'demo/hello' 
  get 'demo/other_hello'
  get 'demo/gf' 
  get 'demo/escape_output'

  #default route = may go away in future versions of the rails 
  #get ':controller(/:action(/:id))'  

  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

    #self.table_name = "admin_users"  - #not needed if Model and table name a matching (except singlular-plural)
    has_and_belongs_to_many :pages

    has_many :section_edits
    has_many :sections, :through => :section_edits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

    belongs_to :subject  # { :optional => true }
    has_many :sections
    has_and_belongs_to_many :admin_users

    scope :visible, lambda { where(:visible => true) }
    scope :invisible, lambda { where(:visible => false) }
    scope :sorted, lambda { order("position ASC") }
    scope :newest_first, lambda { order("created_at DESC") }
    
end

app/models/section.rb
class Section < ApplicationRecord

    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    scope :visible, lambda { where(:visible => true) }
    scope :invisible, lambda { where(:visible => false) }
    scope :sorted, lambda { order("position ASC") }
    scope :newest_first, lambda { order("created_at DESC") }
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord

    belongs_to :admin_user
    belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord

    has_many :pages

    scope :visible, lambda { where(:visible => true) }
    scope :invisible, lambda { where(:visible => false) }
    scope :sorted, lambda { order("position ASC") }
    scope :newest_first, lambda { order("created_at DESC") }
    scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  layout 'admin'

  def index
    render('index')
  end

  def hello
    @myvar = "hello variable"
    @array = [1,2,3,4,5]

    @id = params['id']
    @page = params[:page]

    render('hello')
  end

  def other_hello
     
    #redirect_to(:controller => 'demo', :action => 'hello')
    redirect_to(:action => 'hello')
    
  end

  def gf
    redirect_to('https://gamefreaks.com.au');
  end;

  def escape_output
  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  layout 'admin'
  
  def index
    @pages  = Page.all.sorted
  end
  
  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(pages_params)
    if @page.save
      flash[:notice] = "Page Successfully Created"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(pages_params)
      flash[:notice] = "Page Successfully Updated"
      redirect_to(pages_path)
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "Page '#{@page.name}' Deleted Sucessfully"
    redirect_to(pages_path)
  end

  private def pages_params
    params.require(:page).permit(:name, :position, :visible, :permalink, :subject_id)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  layout 'admin'
  
  def index
    @sections  = Section.all.sorted
  end
  
  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(sections_params)
    if @section.save
      flash[:notice] = "Section Successfully Created"
      redirect_to(sections_path)
    else
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(sections_params)
      flash[:notice] = "Section Successfully Updated"
      redirect_to(sections_path)
    else
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section '#{@section.name}' Deleted Successfully"
    redirect_to(sections_path)
  end

  private def sections_params
    params.require(:section).permit(:name, :position, :visible, :page_id, :content_type, :content)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout 'admin'
  
  def index
    @subjects = Subject.sorted    

  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new(name:'Default name')
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = "Subject Created Sucessfully"
      redirect_to(subjects_path)
    else
      render(new)
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject Updated Successfully"
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    flash[:notice] = "Subject '#{@subject.name}' Deleted Sucessfully"
    @subject.destroy
    redirect_to(subjects_path)
  end

  private def subject_params

    params.require(:subject).permit(:name, :position, :visible)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def status_tag(boolean, options={})
        options[:true_text] ||= ''
        options[:false_text] ||= ''

        if boolean
            content_tag(:span, options[:true_text], class:'status true')
        else
            content_tag(:span, options[:false_text], class:'status false')
        end
    end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/escape_output.html.erb
<% evil_string = "<script>alert('Gotcha!');</script>"%>
<% good_string = "<strong>Welcome to my site!</strong>"%>

<%= evil_string %><br />
<%= raw good_string %><br />

app/views/demo/hello.html.erb
<h1>Hello World from Hello</h1>

<%= 1+1 %> <br />

<% target = "world" %>
<%= "Hello #{target}" %>

<br />


<% @array.each do |n| %>
    <%= n %> <br />
<% end %>
<br />
<%= @myvar %> 

<br />

<%= link_to('Index Page', {:action => 'index'}) %>

<br /> <br />

ID: <%= @id %> <br />
ID: <%= params[:id] %> <br />
Page: <%= @page %> <br />
Next Page: <%= @page.to_i + 1 %>

app/views/demo/index.html.erb
<h1>Hello World from Index</h1>

<a href="/demo/hello">Hello Page - 1</a> <br />
<%= link_to('Hello Page - 2', {:action => 'hello'}) %> <br />
<%= link_to('Hello Page with Parameters', {:action => 'hello', :page => 5, :id => 20}) %>
<br />
<br />
<%= link_to('Subject List', {:controller => 'subjects', :action => 'index'}) %> |
<%= link_to('Page List', {:controller => 'pages', :action => 'index'}) %> |
<%= link_to('Section List', {:controller => 'sections', :action => 'index'}) %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Simple CMS: <%= @page_title || "Admin Area"%></title>
        <style>
        span.status { display: block; width: 10px; height: 10px;
            margin: 0.25em auto; padding: 0; border: 1px solid #000000; }
        span.status.true  { background: green; color: green; }
        span.status.false { background: yellow; color: yellow; }
        </style>

    </head>

    <body>
        <% if !flash[:notice].blank? %>
        <div class="notice">
            <%= flash[:notice] %>
        </div>
        <% end %>
        
        <!-- before yield -->
        <%= yield %> 
        <!-- after yield -->

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
 <table summary="Page form fields">

            <tr>
                <th> Name </th>
                <td> <%= f.text_field(:name) %> </td>
            </tr>

            <tr>
                <th> Position </th>
                <td> <%= f.text_field(:position) %> </td>
            </tr>

            <tr>
                <th> Permalink </th>
                <td> <%= f.text_field(:permalink) %> </td>
            </tr>

            <tr>
                <th> Subject ID </th>
                <td> <%= f.text_field(:subject_id) %> </td>
            </tr>

            <tr>
                <th> Visible </th>
                <td> <%= f.text_field(:visible) %> </td>
            </tr>
        </table>

app/views/pages/delete.html.erb
<%  @page_title = "Delete Page" %>
<%= link_to("<< Back to Pages List", pages_path, :class => "back-link") %>

<div class="pages delete">
    <h2> Delete Page </h2>

    <%= form_for(@page, method:'delete') do |f| %>

        <p> Are you sure you want to permanently delete this Page?<p>
        <p class="reference-name"> <%= f.object.name %> </p>
        
        <div class="form-buttons">
            <%= f.submit("Delete Page") %>
        </div>


    <% end %>


</div>

app/views/pages/edit.html.erb
<%  @page_title = "Edit Page" %>
<%= link_to("<< Back to Page List", pages_path, :class => "back-link") %>

<div class="pages edit">
    <h2> Update Page </h2>

    <%= form_for(@page) do |f| %>

        <%= render(partial: 'form', locals:{f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Update Page") %>
        </div>


    <% end %>


</div>

app/views/pages/index.html.erb
<%  @page_title = "Page List" %>

<div class="pages index">
    <h2> Pages </h2> 

    <%= link_to("Add New Page", new_page_path, :class => "action new") %>
    <br /> <br/>
    <table class="listing" summary="Page List">
        <tr class="header">
            <th>#</th>
            <th>Page Name</th>
            <th>Subject</th>
            <th>Permalink</th>
            <th>Visible</th>
            <th>Actions</th>
        </tr>

        <% @pages.each do |page|  %>
        <tr>
            <td> <%= page.position %> </td>
            <td> <%= page.name %> </td>
            <td> <%= page.subject.name %> </td>
            <td> <%= page.permalink %> </td>
            <td class="center"> <%= status_tag(page.visible) %> </td>
            <td class="actions"> 
               <%= link_to('Show', page_path(page), :class => 'action show') %>
               <%= link_to('Edit', edit_page_path(page), :class => 'action edit') %>
               <%= link_to('Delete', delete_page_path(page), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>

    <br /> <br />
    <%= link_to('Back to Home Page', {controller:'demo', action:'index'}) %>

</div>

app/views/pages/new.html.erb
<%  @page_title = "Create New Page" %>
<%= link_to("<< Back to Page List", pages_path, :class => "back-link") %>

<div class="pages new">
    <h2> Create New Page </h2>

    <%= form_for(@page) do |f| %>

       <%= render(partial: 'form', locals:{f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Create Page") %>
        </div>


    <% end %>


</div>

app/views/pages/show.html.erb
<%  @page_title = "Page Details" %>

<%= link_to("<< Back to Page List", pages_path, :class => "back-link") %>

<div class="pages show">
    <h2> Show Page </h2>
 
    <table summary="page detail view">

        <tr>
           <th> Name </th>
           <td> <%= @page.name %> </td>
        </tr>

        <tr>
           <th> Postion </th>
           <td> <%= @page.position %> </td>
        </tr>

        <tr>
            <th> Subject </th>
            <td> <%= @page.subject.name %> </td>
        </tr>

        <tr>
            <th> Permalink </th>
            <td> <%= @page.permalink %> </td>
        </tr>

        <tr>
           <th> Visible </th>
           <td> <%= @page.visible ? 'Yes' : 'No' %> </td>
        </tr>

        <tr>
           <th> Created </th>
           <td> <%= @page.created_at %> </td>
        </tr>

        <tr>
           <th> Updated </th>
           <td> <%= @page.updated_at %> </td>
        </tr>
    </table>
</div>

app/views/sections/_form.html.erb
 <table summary="Section form fields">

            <tr>
                <th> Name </th>
                <td> <%= f.text_field(:name) %> </td>
            </tr>

            <tr>
                <th> Position </th>
                <td> <%= f.text_field(:position) %> </td>
            </tr>

            <tr>
                <th> Page ID </th>
                <td> <%= f.text_field(:page_id) %> </td>
            </tr>

            <tr>
                <th> Content Type </th>
                <td> <%= f.text_field(:content_type) %> </td>
            </tr>
            
            <tr>
                <th> Content </th>
                <td> <%= f.text_area(:content) %> </td>
            </tr>

            <tr>
                <th> Visible </th>
                <td> <%= f.text_field(:visible) %> </td>
            </tr>
        </table>

app/views/sections/delete.html.erb
<%  @page_title = "Delete Section" %>

<%= link_to("<< Back to Sections List", sections_path, :class => "back-link") %>

<div class="sections delete">
    <h2> Delete Section </h2>

    <%= form_for(@section, method:'delete') do |f| %>

        <p> Are you sure you want to permanently delete this Section?<p>
        <p class="reference-name"> <%= f.object.name %> </p>
        
        <div class="form-buttons">
            <%= f.submit("Delete Section") %>
        </div>


    <% end %>


</div>

app/views/sections/edit.html.erb
<%  @page_title = "Edit Section" %>
<%= link_to("<< Back to Section List", sections_path, :class => "back-link") %>

<div class="sections edit">
    <h2> Update Section </h2>

    <%= form_for(@section) do |f| %>

        <%= render(partial: 'form', locals:{f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Update Section") %>
        </div>


    <% end %>


</div>

app/views/sections/index.html.erb
<%  @page_title = "Section List" %>

<div class="sections index">
    <h2> Sections </h2> 

    <%= link_to("Add New Section", new_section_path, :class => "action new") %>
    <br /> <br/>
    <table class="listing" summary="Section List">
        <tr class="header">
            <th>#</th>
            <th>Section</th>
            <th>Page</th>
            <th>Visible</th>
            <th>Actions</th>
        </tr>

        <% @sections.each do |section|  %>
        <tr>
            <td> <%= section.position %> </td>
            <td> <%= section.name %> </td>
            <td> <%= section.page.name %> </td>
            <td class="center"> <%= status_tag(section.visible) %> </td>
            <td class="actions"> 
               <%= link_to('Show', section_path(section), :class => 'action show') %>
               <%= link_to('Edit', edit_section_path(section), :class => 'action edit') %>
               <%= link_to('Delete', delete_section_path(section), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>

    <br /> <br />
    <%= link_to('Back to Home Page', {controller:'demo', action:'index'}) %>

</div>

app/views/sections/new.html.erb
<%  @page_title = "Create New Section" %>
<%= link_to("<< Back to Section List", sections_path, :class => "back-link") %>

<div class="sections new">
    <h2> Create New Section </h2>

    <%= form_for(@section) do |f| %>

       <%= render(partial: 'form', locals:{f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Create Section") %>
        </div>


    <% end %>


</div>

app/views/sections/show.html.erb
<%  @page_title = "Section Details" %>

<%= link_to("<< Back to Section List", sections_path, :class => "back-link") %>

<div class="sections show">
    <h2> Show Section </h2>
 
    <table summary="section detail view">

        <tr>
           <th> Name </th>
           <td> <%= @section.name %> </td>
        </tr>

        <tr>
           <th> Postion </th>
           <td> <%= @section.position %> </td>
        </tr>

        <tr>
            <th> Page </th>
            <td> <%= @section.page.name %> </td>
        </tr>

        <tr>
            <th> Content Type </th>
            <td> <%= @section.content_type %> </td>
        </tr>

        <tr>
            <th> Content </th>
            <td> <%= @section.content %> </td>
        </tr>

        <tr>
           <th> Visible </th>
           <td> <%= @section.visible ? 'Yes' : 'No' %> </td>
        </tr>

        <tr>
           <th> Created </th>
           <td> <%= @section.created_at %> </td>
        </tr>

        <tr>
           <th> Updated </th>
           <td> <%= @section.updated_at %> </td>
        </tr>
    </table>
</div>

app/views/subjects/_form.html.erb
        <table summary="Subject form fields">
            <tr>
                <th> Name </th>
                <td> <%= f.text_field(:name) %> </td>
            </tr>

            <tr>
                <th> Position </th>
                <td> <%= f.text_field(:position) %> </td>
            </tr>

            <tr>
                <th> Visible </th>
                <td> <%= f.text_field(:visible) %> </td>
            </tr>
        </table>

app/views/subjects/delete.html.erb
<%  @page_title = "Delete Subject" %>
<%= link_to("<< Back to Subject List", subjects_path, :class => "back-link") %>

<div class="subjects delete">
    <h2> Delete Subject </h2>

    <%= form_for(@subject, method:'delete') do |f| %>

        <p> Are you sure you want to permanently delete this subject?<p>
        <p class="reference-name"> <%= f.object.name %> </p>
        
        <div class="form-buttons">
            <%= f.submit("Delete Subject") %>
        </div>


    <% end %>


</div>

app/views/subjects/edit.html.erb
<%  @page_title = "Edit Subject" %>

<%= link_to("<< Back to Subject List", subjects_path, :class => "back-link") %>

<div class="subjects edit">
    <h2> Update Subject </h2>

    <%= form_for(@subject) do |f| %>

        <%= render(partial: 'form', locals: {f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Update Subject") %>
        </div>


    <% end %>


</div>

app/views/subjects/index.html.erb
<%  @page_title = "Subject List" %>

<div class="subjects index">
    <h2> Subjects </h2> 

    <%= link_to("Add New Subject", new_subject_path, :class => "action new") %>
    <br /> <br/>
    <table class="listing" summary="Subject List">
        <tr class="header">
            <th>#</th>
            <th>Subject</th>
            <th>Visible</th>
            <th>Pages</th>
            <th>Actions</th>
        </tr>

        <% @subjects.each do |subject|  %>
        <tr>
            <td> <%= subject.position %> </td>
            <td> <%= subject.name %> </td>
            <td class="center"> <%= status_tag(subject.visible) %> </td>
            <td class="center"> <%= subject.pages.size %> </td>
            <td class="actions"> 
               <%= link_to('Show', subject_path(subject), :class => 'action show') %>
               <%= link_to('Edit', edit_subject_path(subject), :class => 'action edit') %>
               <%= link_to('Delete', delete_subject_path(subject), :class => 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>

    <br /> <br />
    <%= link_to('Back to Home Page', {controller:'demo', action:'index'}) %>

</div>

app/views/subjects/new.html.erb
<%  @page_title = "Create New Subject" %>
<%= link_to("<< Back to Subject List", subjects_path, :class => "back-link") %>

<div class="subjects new">
    <h2> Create Subject </h2>

    <%= form_for(@subject) do |f| %>

        <%= render(partial: 'form', locals: {f:f}) %>

        <div class="form-buttons">
            <%= f.submit("Create Subject") %>
        </div>

    <% end %>


</div>

app/views/subjects/show.html.erb
<%  @page_title = "Subject Details" %>

<%= link_to("<< Back to Subject List", subjects_path, :class => "back-link") %>

<div class="subjects show">
    <h2> Show Subject </h2>
 
    <table summary="Subject detail view">

        <tr>
           <th> Name </th>
           <td> <%= @subject.name %> </td>
        </tr>

        <tr>
           <th> Postion </th>
           <td> <%= @subject.position %> </td>
        </tr>

        <tr>
           <th> Visible </th>
           <td> <%= @subject.visible ? 'Yes' : 'No' %> </td>
        </tr>

        <tr>
           <th> Created </th>
           <td> <%= @subject.created_at %> </td>
        </tr>

        <tr>
           <th> Updated </th>
           <td> <%= @subject.updated_at %> </td>
        </tr>
    </table>
</div>